apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy: {}
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: 459929160817.dkr.ecr.us-east-1.amazonaws.com/sandbox:cb881fd2be90b3ff0f98f4ba803084db1be566fb
        name: nginx
        resources: {}